#!/usr/bin/env bash
#
# script to clear out all containers
echo "Running command to clear out all existing containers..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker container rm -f $(docker container ls -aq)