#!/usr/bin/env bash
#
# script to start the Openspeedtest container
echo "Starting Openspeedtest container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker run --restart=unless-stopped --name=openspeedtest -d -p 80:8080 openspeedtest/latest