#!/usr/bin/env bash
#
# script to start the SBC wifiexplorer-sensor container
echo "Stopping wifiexplorer-sensor container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker container stop wifiexplorer-sensor