#!/usr/bin/env bash
#
# script to start the SBC tcpdumper container
echo "Starting tcpdumper container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker run -d --net host --privileged --restart always --name tcpdumper sbcprobe/tcpdumper