#!/usr/bin/env bash
#
# script to clear out all containers
echo "Running command to clear out all existing images..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker rmi -f $(docker images -q)