#!/usr/bin/env bash
#
# script to start the SBC Hotspot container
echo "Stopping tftpd container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker container stop tftpd