#!/usr/bin/env bash
#
# script to remove the SBC tftpd container (image stays in-place)
echo "Removing the tftpd container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker container rm -f tftpd