#!/usr/bin/env bash
#
# script to destroy the SBC Hotspot container
echo "Stopping & removing the hotspot container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker container rm -f hotspot