#!/usr/bin/env bash
#
# script to start the SBC wireless console container
echo "Starting wconsole container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker run -d -it --restart always --net host --privileged --name wconsole sbcprobe/wconsole:latest