#!/usr/bin/env bash
#
# script to stop the SBC tcpdumper container
echo "Stopping tcpdumper container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker container stop tcpdumper