#!/usr/bin/env bash
#
# script to start the SBC tftpd container
echo "Starting tftpd container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker run -d -i -t --restart always -p 69:69/udp  -v /tmp:/tmp:rw --name tftpd sbcprobe/tftpd:latest