#!/usr/bin/env bash
#
# script to remove the SBC Hotspot container (image stays in-place)
echo "Removing the hotspot container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker container rm -f hotspot