#!/usr/bin/env bash
#
# script to destroy the SBC wifiexplorer-sensor container
echo "Stopping and removing the wifiexplorer-sensor container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker container rm -f wifiexplorer-sensor