#!/usr/bin/env bash
#
# script to start the iperf3 container
echo "Starting iperf3 container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker run --restart=unless-stopped -t -p 5201:5201 -p 5201:5201/udp --name iperf3 taoyou/iperf3-alpine:latest