#!/usr/bin/env bash
#
# script to destroy the iperf3 container
echo "Stopping & removing the iperf3 container..."
read -p "Are you sure? (Y/N)" -n 1 -r
echo 

if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

docker container rm -f iperf3