#!/usr/bin/env bash

set -e

# script to start the SBC tcpdumper container

run () {
    echo "Starting tcpdumper container..."
    read -p "Are you sure? (Y/N)" -n 1 -r
    echo 

    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        exit 1
    fi

    # include password if passed on CLI
    PWD=""
    if [ ! -z $1 ]; then
        PWD=" -e SSH_PWD=$1 "
    fi

    docker run -d --net host --privileged --restart always --name tcpdumper ${PWD} sbcprobe/tcpdumper

    exit 0
}

help () {
    echo "Useage:"
    echo
    echo "    sbc_tcpdumper_start [ -p <ssh_pwd> ]"
    echo "    sbc_tcpdumper_start -h"
    echo 

    exit 0

}

case "$1" in
  -h)
        help
        ;;
  -p)
        run $2
        ;;
  *)
        run
        ;;
esac